// src/optionsPage.svelte
<script>
    import {onMount} from 'svelte'
    import defaults from './defaultOptions'

    let options = defaults

    onMount(() => {
        chrome.storage.local.get(defaults, (data) => {
            options = data
        })
    })

    // TODO: Add feedback
    function handleSave() {
        chrome.storage.local.set(options)
    }

    // TODO: Add feedback + confirmation
    function handleReset() {
        chrome.storage.local.set(defaults)
        location.reload()
    }
</script>

<style>
    :global(html) {
        background: rgb(78, 89, 101);
    }

    .section {
        max-width: 30rem;
        background: white;
    }

    .input {
        width: 5em;
        vertical-align: baseline;
    }
</style>

<main class="container">
    <section class="section">
        <h2 class="title is-5">Basic</h2>
        <div class="field">
            <div class="control">
                <label class="checkbox">
                    <input type="checkbox"
                           bind:checked={$options.stickyScroll}
                    />{' '}
                    Scroll without holding down the mouse button
                </label>
            </div>
            <div class="control">
                ...if moving less than{' '}
                <input
                        type="number"
                        class="input is-small"
                        bind:value={$options.moveThreshold}
                        aria-label="..if moving less than X pixels"
                />{' '}
                pixels
            </div>
        </div>
        <div class="field">
            <div class="control">
                Scroll if moving more than{' '}
                <input
                        type="number"
                        class="input is-small"
                        bind:value={$options.dragThreshold}
                        aria-label="Drag threshold in pixels"
                />{' '}
                pixels
            </div>
        </div>
        <div class="field">
            <div class="control">
                <label class="checkbox">
                    <input
                            type="checkbox"
                            bind:checked={$options.middleClick}
                    />{' '}
                    Scroll by using (Middle Click)
                </label>
            </div>
        </div>
        <div class="field">
            <div class="control">
                <label class="checkbox">
                    <input
                            type="checkbox"
                            bind:checked={$options.ctrlClick}
                    />{' '}
                    Scroll by using (Ctrl/⌘ + Left Click)
                </label>
            </div>
        </div>
    </section>
    <section class="section">
        <h2 class="title is-5">Speed</h2>
        <div class="field">
            <div class="control">
                Move speed:{' '}
                <input type="number"
                       class="input is-small"
                       bind:value={$options.moveSpeed}
                       aria-label="Move speed in pixels"
                />{' '}
                (lower is faster)
            </div>
        </div>
        <div class="field">
            <div class="control">
                <label class="checkbox">
                    <input type="checkbox"
                           bind:checked={$options.sameSpeed}
                    />{' '}
                    Scroll at the same speed (ignore mouse movement)
                </label>
            </div>
        </div>
        <div class="field">
            <div class="control">
                <label class="checkbox">
                    <input type="checkbox"
                           bind:checked={$options.shouldCap}
                    />{' '}
                    Don't scroll faster than{' '}
                    <input type="number"
                           class="input is-small"
                           bind:value={$options.capSpeed}
                           aria-label="Speed cap in pixels"
                    />{' '}
                    pixels
                </label>
            </div>
        </div>
    </section>
    <section class="section">
        <h2 class="title is-5">Advanced</h2>
        <div class="field">
            <div class="control">
                <label class="checkbox">
                    <input type="checkbox"
                           name="innerScroll"
                           bind:checked={$options.innerScroll}
                    />{' '}
                    Scroll on inner elements
                </label>
            </div>
        </div>
        <div class="field">
            <div class="control">
                <label class="checkbox">
                    <input type="checkbox"
                           name="scrollOnLinks"
                           bind:checked={$options.scrollOnLinks}
                    />{' '}
                    Scroll when clicking on a link or textarea
                </label>
            </div>
        </div>
    </section>
    <section class="section">
        <div class="buttons">
            <button class="button is-primary" on:click={handleSave}>
                Save
            </button>
            <button class="button is-danger" on:click={handleReset}>
                Reset
            </button>
        </div>
    </section>
</main>

// src/optionsPage.jsx
import React, { useState, useEffect } from 'react'
import ReactDOM from 'react-dom'
import defaults from './defaultOptions'
import 'bulma/css/bulma.min.css'
import './optionsPage.css'

function OptionsPage() {
    const [formData, setFormData] = useState(defaults)

    useEffect(() => {
        chrome.storage.local.get(defaults, (options) => {
            setFormData(options)
        })
    }, [])

    function handleChange(e) {
        setFormData({ ...formData, [e.target.name]: e.target.value })
        chrome.storage.local.set(formData)
    }

    function handleReset() {
        chrome.storage.local.set(defaults)
        location.reload()
    }

    return (
        <main className="container">
            <section className="section">
                <h2 className="title is-5">Basic</h2>
                <div className="field">
                    <div className="control">
                        <label className="checkbox">
                            <input
                                type="checkbox"
                                name="stickyScroll"
                                checked={formData.stickyScroll}
                                onChange={handleChange}
                            />{' '}
                            Scroll without holding down the mouse button
                        </label>
                    </div>
                    <div className="control">
                        ...if moving less than{' '}
                        <input
                            type="number"
                            className="input is-small"
                            name="moveThreshold"
                            value={formData.moveThreshold}
                            onChange={handleChange}
                        />{' '}
                        pixels
                    </div>
                </div>
                <div className="field">
                    <div className="control">
                        Scroll if moving more than{' '}
                        <input
                            type="number"
                            className="input is-small"
                            name="dragThreshold"
                            value={formData.dragThreshold}
                            onChange={handleChange}
                        />{' '}
                        pixels
                    </div>
                </div>
                <div className="field">
                    <div className="control">
                        <label className="checkbox">
                            <input
                                type="checkbox"
                                name="middleClick"
                                checked={formData.middleClick}
                                onChange={handleChange}
                            />{' '}
                            Scroll by using (Middle Click)
                        </label>
                    </div>
                </div>
                <div className="field">
                    <div className="control">
                        <label className="checkbox">
                            <input
                                type="checkbox"
                                name="ctrlClick"
                                checked={formData.ctrlClick}
                                onChange={handleChange}
                            />{' '}
                            Scroll by using (Ctrl/⌘ + Left Click)
                        </label>
                    </div>
                </div>
            </section>
            <section className="section">
                <h2 className="title is-5">Speed</h2>
                <div className="field">
                    <div className="control">
                        Move speed:{' '}
                        <input
                            type="number"
                            className="input is-small"
                            name="moveSpeed"
                            value={formData.moveSpeed}
                            onChange={handleChange}
                        />{' '}
                        (lower is faster)
                    </div>
                </div>
                <div className="field">
                    <div className="control">
                        <label className="checkbox">
                            <input
                                type="checkbox"
                                name="sameSpeed"
                                value={formData.sameSpeed}
                                onChange={handleChange}
                            />{' '}
                            Scroll at the same speed (ignore mouse movement)
                        </label>
                    </div>
                </div>
                <div className="field">
                    <div className="control">
                        <label className="checkbox">
                            <input
                                type="checkbox"
                                name="shouldCap"
                                checked={formData.shouldCap}
                                onChange={handleChange}
                            />{' '}
                            Don't scroll faster than{' '}
                            <input
                                type="number"
                                className="input is-small"
                                name="capSpeed"
                                value={formData.capSpeed}
                                onChange={handleChange}
                            />{' '}
                            pixels
                        </label>
                    </div>
                </div>
            </section>
            <section className="section">
                <h2 className="title is-5">Advanced</h2>
                <div className="field">
                    <div className="control">
                        <label className="checkbox">
                            <input
                                type="checkbox"
                                name="innerScroll"
                                checked={formData.innerScroll}
                                onChange={handleChange}
                            />{' '}
                            Scroll on inner elements
                        </label>
                    </div>
                </div>
                <div className="field">
                    <div className="control">
                        <label className="checkbox">
                            <input
                                type="checkbox"
                                name="scrollOnLinks"
                                checked={formData.scrollOnLinks}
                                onChange={handleChange}
                            />{' '}
                            Scroll when clicking on a link or textarea
                        </label>
                    </div>
                </div>
            </section>
            <section className="section">
                <div className="buttons">
                    <button className="button is-danger" onClick={handleReset}>
                        Reset
                    </button>
                </div>
            </section>
        </main>
    )
}

ReactDOM.render(<OptionsPage />, document.getElementById('root'))
