// src/OptionsPage.svelte
<script>
    import { onMount } from 'svelte'
    import { writable } from 'svelte/store'
    import defaults from './defaultOptions'
    import { _ } from 'svelte-intl'

    let options = writable(defaults)

    onMount(() => {
        chrome.storage.local.get(defaults, (data) => {
            options.set(data)
        })

        options.subscribe((data) => {
            chrome.storage.local.set(data)
        })
    })

    function handleReset() {
        options.set(defaults)
    }
</script>

<style>
    .section {
        margin-top: 2rem;
        max-width: 30rem;
    }

    .input {
        display: inline;
        width: 5em;
        vertical-align: baseline;
    }

    .control {
        margin-top: 3px;
        margin-bottom: 3px;
    }
</style>

<main class="container">
    <section class="section">
        <h2 class="title is-5">{$_('Basic')}</h2>
        <div class="field">
            <div class="control">
                <label class="checkbox">
                    <input type="checkbox"
                           bind:checked={$options.stickyScroll}
                    />{' '}
                    {$_('Scroll without holding down the mouse button')}
                </label>
            </div>
            <div class="control">
                {$_('...if moving less than')}{' '}
                <input
                        type="number"
                        class="input is-small"
                        bind:value={$options.moveThreshold}
                        aria-label={$_('...if moving less than X pixels')}
                />{' '}
                {$_('pixels')}
            </div>
        </div>
        <div class="field">
            <div class="control">
                {$_('Scroll if moving more than')}{' '}
                <input
                        type="number"
                        class="input is-small"
                        bind:value={$options.dragThreshold}
                        aria-label={$_('Drag threshold in pixels')}
                />{' '}
                {$_('pixels')}
            </div>
        </div>
        <div class="field">
            <div class="control">
                <label class="checkbox">
                    <input
                            type="checkbox"
                            bind:checked={$options.middleClick}
                    />{' '}
                    {$_('Scroll by using (Middle Click)')}
                </label>
            </div>
        </div>
        <div class="field">
            <div class="control">
                <label class="checkbox">
                    <input
                            type="checkbox"
                            bind:checked={$options.ctrlClick}
                    />{' '}
                    {$_('Scroll by using (Ctrl/⌘ + Left Click)')}
                </label>
            </div>
        </div>
    </section>
    <section class="section">
        <h2 class="title is-5">{$_('Speed')}</h2>
        <div class="field">
            <div class="control">
                {$_('Move speed:')}{' '}
                <input type="number"
                       class="input is-small"
                       bind:value={$options.moveSpeed}
                       aria-label={$_('Move speed in pixels')}
                />{' '}
                {$_('(lower is faster)')}
            </div>
        </div>
        <div class="field">
            <div class="control">
                <label class="checkbox">
                    <input type="checkbox"
                           bind:checked={$options.sameSpeed}
                    />{' '}
                    {$_('Scroll at the same speed (ignore mouse movement)')}
                </label>
            </div>
        </div>
        <div class="field">
            <div class="control">
                <label class="checkbox">
                    <input type="checkbox"
                           bind:checked={$options.shouldCap}
                    />{' '}
                    {$_('Don\'t scroll faster than')}{' '}
                    <input type="number"
                           class="input is-small"
                           bind:value={$options.capSpeed}
                           aria-label={$_('Speed cap in pixels')}
                    />{' '}
                    {$_('pixels')}
                </label>
            </div>
        </div>
    </section>
    <section class="section">
        <h2 class="title is-5">{$_('Advanced')}</h2>
        <div class="field">
            <div class="control">
                <label class="checkbox">
                    <input type="checkbox"
                           name="innerScroll"
                           bind:checked={$options.innerScroll}
                    />{' '}
                    {$_('Scroll on inner elements')}
                </label>
            </div>
        </div>
        <div class="field">
            <div class="control">
                <label class="checkbox">
                    <input type="checkbox"
                           name="scrollOnLinks"
                           bind:checked={$options.scrollOnLinks}
                    />{' '}
                    {$_('Scroll when clicking on a link or textarea')}
                </label>
            </div>
        </div>
    </section>
    <section class="section">
        <div class="buttons">
            <button class="button" on:click={handleReset}>
                {$_('Reset')}
            </button>
        </div>
    </section>
</main>

// src/optionsPage.jsx
import React, { useState, useEffect } from 'react'
import ReactDOM from 'react-dom'
import defaults from './defaultOptions'
import 'bulma/css/bulma.min.css'
import './optionsPage.css'

function OptionsPage() {
    const [formData, setFormData] = useState(defaults)

    useEffect(() => {
        chrome.storage.local.get(defaults, (options) => {
            setFormData(options)
        })
    }, [])

    function handleChange(e) {
        setFormData({ ...formData, [e.target.name]: e.target.value })
        chrome.storage.local.set(formData)
    }

    function handleReset() {
        chrome.storage.local.set(defaults)
        location.reload()
    }

    return (
        <main className="container">
            <section className="section">
                <h2 className="title is-5">Basic</h2>
                <div className="field">
                    <div className="control">
                        <label className="checkbox">
                            <input
                                type="checkbox"
                                name="stickyScroll"
                                checked={formData.stickyScroll}
                                onChange={handleChange}
                            />{' '}
                            Scroll without holding down the mouse button
                        </label>
                    </div>
                    <div className="control">
                        ...if moving less than{' '}
                        <input
                            type="number"
                            className="input is-small"
                            name="moveThreshold"
                            value={formData.moveThreshold}
                            onChange={handleChange}
                        />{' '}
                        pixels
                    </div>
                </div>
                <div className="field">
                    <div className="control">
                        Scroll if moving more than{' '}
                        <input
                            type="number"
                            className="input is-small"
                            name="dragThreshold"
                            value={formData.dragThreshold}
                            onChange={handleChange}
                        />{' '}
                        pixels
                    </div>
                </div>
                <div className="field">
                    <div className="control">
                        <label className="checkbox">
                            <input
                                type="checkbox"
                                name="middleClick"
                                checked={formData.middleClick}
                                onChange={handleChange}
                            />{' '}
                            Scroll by using (Middle Click)
                        </label>
                    </div>
                </div>
                <div className="field">
                    <div className="control">
                        <label className="checkbox">
                            <input
                                type="checkbox"
                                name="ctrlClick"
                                checked={formData.ctrlClick}
                                onChange={handleChange}
                            />{' '}
                            Scroll by using (Ctrl/⌘ + Left Click)
                        </label>
                    </div>
                </div>
            </section>
            <section className="section">
                <h2 className="title is-5">Speed</h2>
                <div className="field">
                    <div className="control">
                        Move speed:{' '}
                        <input
                            type="number"
                            className="input is-small"
                            name="moveSpeed"
                            value={formData.moveSpeed}
                            onChange={handleChange}
                        />{' '}
                        (lower is faster)
                    </div>
                </div>
                <div className="field">
                    <div className="control">
                        <label className="checkbox">
                            <input
                                type="checkbox"
                                name="sameSpeed"
                                value={formData.sameSpeed}
                                onChange={handleChange}
                            />{' '}
                            Scroll at the same speed (ignore mouse movement)
                        </label>
                    </div>
                </div>
                <div className="field">
                    <div className="control">
                        <label className="checkbox">
                            <input
                                type="checkbox"
                                name="shouldCap"
                                checked={formData.shouldCap}
                                onChange={handleChange}
                            />{' '}
                            Don't scroll faster than{' '}
                            <input
                                type="number"
                                className="input is-small"
                                name="capSpeed"
                                value={formData.capSpeed}
                                onChange={handleChange}
                            />{' '}
                            pixels
                        </label>
                    </div>
                </div>
            </section>
            <section className="section">
                <h2 className="title is-5">Advanced</h2>
                <div className="field">
                    <div className="control">
                        <label className="checkbox">
                            <input
                                type="checkbox"
                                name="innerScroll"
                                checked={formData.innerScroll}
                                onChange={handleChange}
                            />{' '}
                            Scroll on inner elements
                        </label>
                    </div>
                </div>
                <div className="field">
                    <div className="control">
                        <label className="checkbox">
                            <input
                                type="checkbox"
                                name="scrollOnLinks"
                                checked={formData.scrollOnLinks}
                                onChange={handleChange}
                            />{' '}
                            Scroll when clicking on a link or textarea
                        </label>
                    </div>
                </div>
            </section>
            <section className="section">
                <div className="buttons">
                    <button className="button is-danger" onClick={handleReset}>
                        Reset
                    </button>
                </div>
            </section>
        </main>
    )
}

ReactDOM.render(<OptionsPage />, document.getElementById('root'))
